
services:
  grafana:
    image: "grafana/grafana:${GRAF_TAG-latest}"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD-.}/grafana-storage:/var/lib/grafana"

  prometheus:
    image: "prom/prometheus:${PROM_TAG-latest}"
    ports:
      - "9090:9090"
    volumes:
      - "${PWD-.}/prometheus:/etc/prometheus"

  node-exporter:
    image: "prom/node-exporter:${PROM_TAG-latest}"
    ports:
      - "9100:9100"
