version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - "${PWD-.}/elasticsearch:/usr/share/elasticsearch/data"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    volumes:
      - "${PWD-.}/logstash:/usr/share/logstash/pipeline"
      - "${PWD-.}/data:/data"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"
